import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Note from "@/components/Note";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Bassim's Personal Website",
    description: "Generated by create next app",
};

export default function RootLayout() {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex">
                    <Sidebar />
                    <div className="flex-1 ml-64">
                        <Note />
                    </div>
                </div>
            </body>
        </html>
    );
}